# Generated by Django 3.0.3 on 2020-05-02 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pointage', '0002_auto_20200424_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('manager', models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='pointage.Employe')),
            ],
        ),
    ]
