# Generated by Django 3.0.3 on 2020-05-27 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pointage', '0001_initial'),
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pointage.Employe'),
        ),
    ]
