# Generated by Django 3.0.3 on 2020-05-02 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0003_auto_20200502_0658'),
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pointage.Employe'),
        ),
    ]
