# Generated by Django 3.0.3 on 2020-05-26 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_team_manager'),
        ('dash', '0002_auto_20200502_0702'),
    ]

    operations = [
    ]
