# Generated by Django 3.0.3 on 2020-06-25 15:28

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Employé'), (2, 'Manager'), (3, 'Responsable')], null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iwssad', models.BooleanField(default=False)),
                ('finger_id', models.PositiveSmallIntegerField(blank=True, unique=True)),
                ('is_uploaded', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Date naissance')),
                ('birthplace', models.CharField(blank=True, max_length=120)),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Adresse')),
                ('phone1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Téléphone professionnel')),
                ('phone2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Téléphone personnel')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Description')),
                ('picture', models.ImageField(default='images/nounours.png', upload_to='images/', verbose_name='Photo de profil')),
                ('gender', models.CharField(blank=True, choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1, null=True, verbose_name='Genre')),
                ('fonction', models.CharField(blank=True, default='.', max_length=200, null=True, verbose_name='Fonction')),
                ('observation', models.CharField(blank=True, max_length=300, null=True, verbose_name='Remarque')),
            ],
        ),
        migrations.CreateModel(
            name='Planing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, default='team', max_length=150, null=True, unique=True, verbose_name="Nom de l'équipe")),
                ('description', models.CharField(blank=True, max_length=400, null=True, verbose_name="Déscription de l'équipe")),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_team', to='pointage.Employe', verbose_name="manager de l'équipe")),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('day', models.DateField(blank=True, null=True)),
                ('he', models.TimeField(blank=True, null=True)),
                ('hs', models.TimeField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pointage.Employe')),
            ],
        ),
        migrations.AddField(
            model_name='employe',
            name='planing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pemployes', to='pointage.Planing'),
        ),
        migrations.AddField(
            model_name='employe',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='pointage.Team'),
        ),
        migrations.AddField(
            model_name='employe',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jds', models.PositiveIntegerField(blank=True, choices=[(5, 'Samedi'), (6, 'Dimanche'), (0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi')], null=True)),
                ('he1', models.TimeField(blank=True, null=True)),
                ('hs1', models.TimeField(blank=True, null=True)),
                ('he2', models.TimeField(blank=True, null=True)),
                ('hs2', models.TimeField(blank=True, null=True)),
                ('planing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planing_days', to='pointage.Planing')),
            ],
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_day', models.DateTimeField(blank=True, null=True)),
                ('exit_day', models.DateField(blank=True, null=True)),
                ('team_name', models.CharField(max_length=250, null=True)),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affected_set', to='pointage.Employe')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pointage.Team')),
            ],
        ),
    ]
