# Generated by Django 3.0.3 on 2020-06-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='fonction',
            field=models.CharField(blank=True, default='.', max_length=200, null=True, verbose_name='Fonction'),
        ),
    ]
