# Generated by Django 3.0.3 on 2020-06-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Description'),
        ),
    ]
