# Generated by Django 3.0.3 on 2020-06-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='gendre',
            field=models.CharField(blank=True, choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1, null=True, verbose_name='Genre'),
        ),
    ]
