# Generated by Django 3.0.3 on 2020-06-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='exit_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
