# Generated by Django 3.0.3 on 2020-04-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employe',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='birthplace',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='employe',
            name='observation',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='employe',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
