# Generated by Django 3.0.3 on 2020-06-04 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0002_employe_gendre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employe',
            old_name='gendre',
            new_name='gender',
        ),
    ]
