# Generated by Django 3.0.3 on 2020-06-05 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0002_auto_20200605_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='planing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planing_days', to='pointage.Planing'),
        ),
    ]
