# Generated by Django 3.0.3 on 2020-06-25 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0002_auto_20200625_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pointage.Team'),
        ),
    ]
