# Generated by Django 3.0.3 on 2020-05-27 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0002_auto_20200527_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='man',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pointage.Employe', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='employe',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pointage.Team'),
        ),
    ]
