# Generated by Django 3.0.3 on 2020-06-17 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0002_auto_20200616_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='planing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pemployes', to='pointage.Planing'),
        ),
    ]
