# Generated by Django 3.0.3 on 2020-06-14 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0002_employe_fonction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name="Déscription de l'équipe"),
        ),
        migrations.AlterField(
            model_name='team',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_team', to='pointage.Employe', verbose_name="manager de l'équipe"),
        ),
        migrations.AlterField(
            model_name='team',
            name='titre',
            field=models.CharField(blank=True, default='team', max_length=150, null=True, verbose_name="Nom de l'équipe"),
        ),
    ]
