# Generated by Django 3.0.3 on 2020-05-02 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
        ('pointage', '0002_auto_20200424_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='team_id',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='dash.Team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employe',
            name='phone',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
