# Generated by Django 3.0.3 on 2020-06-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0003_auto_20200625_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectation',
            name='team_name',
            field=models.CharField(default='default', max_length=250),
            preserve_default=False,
        ),
    ]
