# Generated by Django 3.0.3 on 2020-06-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0003_auto_20200604_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='he1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='he2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='hs1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='hs2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='phone1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Téléphone professionnel'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='phone2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Téléphone personnel'),
        ),
    ]
