# Generated by Django 3.0.3 on 2020-05-02 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_auto_20200502_0702'),
        ('pointage', '0003_auto_20200502_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='team_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dash.Team'),
        ),
    ]
