# Generated by Django 3.0.3 on 2020-06-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0004_auto_20200618_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='titre',
            field=models.CharField(blank=True, default='team', max_length=150, null=True, unique=True, verbose_name="Nom de l'équipe"),
        ),
    ]
