# Generated by Django 3.0.3 on 2020-06-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0004_auto_20200605_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='day',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
