# Generated by Django 3.0.3 on 2020-05-27 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0005_auto_20200527_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='pointage.Team'),
        ),
    ]
