# Generated by Django 3.0.3 on 2020-06-25 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0005_auto_20200625_1430'),
        ('pointage', '0002_auto_20200624_1409'),
    ]

    operations = [
    ]
