# Generated by Django 3.0.3 on 2020-06-21 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0005_auto_20200618_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='affectation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_day', models.DateField(auto_now=True, null=True)),
                ('exit_day', models.DateField(blank=True, null=True)),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affected_set', to='pointage.Employe')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pointage.Team')),
            ],
        ),
    ]
