# Generated by Django 3.0.3 on 2020-06-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0005_auto_20200618_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='observation',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Remarque'),
        ),
    ]
