# Generated by Django 3.0.3 on 2020-06-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0006_auto_20200621_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Description'),
        ),
    ]
