# Generated by Django 3.0.3 on 2020-05-05 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0006_auto_20200504_0334'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employe',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='employe',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
