# Generated by Django 3.0.3 on 2020-06-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0006_affectation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='enter_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
