# Generated by Django 3.0.3 on 2020-05-27 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0006_auto_20200527_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='man',
        ),
        migrations.AddField(
            model_name='team',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='man', to='pointage.Employe', verbose_name=''),
        ),
    ]
