# Generated by Django 3.0.3 on 2020-06-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0007_auto_20200625_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='enter_day',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='exit_day',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
