# Generated by Django 3.0.3 on 2020-05-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0007_auto_20200505_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='finger_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='picture',
            field=models.ImageField(default='images/nounours.png', upload_to='images/'),
        ),
    ]
