# Generated by Django 3.0.3 on 2020-05-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0007_auto_20200505_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='finger_id',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='phone',
            field=models.CharField(blank=True, max_length=200, verbose_name='telephone 1'),
        ),
    ]
