# Generated by Django 3.0.3 on 2020-06-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0007_auto_20200604_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='jds',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (7, 'Dimanche')], null=True),
        ),
    ]
