# Generated by Django 3.0.3 on 2020-06-06 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0005_auto_20200606_1432'),
        ('pointage', '0008_auto_20200604_2323'),
    ]

    operations = [
    ]
