# Generated by Django 3.0.3 on 2020-05-26 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0009_auto_20200523_1240'),
        ('pointage', '0008_auto_20200509_0731'),
    ]

    operations = [
    ]
