# Generated by Django 3.0.3 on 2020-06-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0009_merge_20200606_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
