# Generated by Django 3.0.3 on 2020-06-01 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0009_auto_20200601_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='planing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pointage.Planing'),
        ),
    ]
