# Generated by Django 3.0.3 on 2020-06-01 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0010_employe_planing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jour',
            new_name='Day',
        ),
        migrations.RenameField(
            model_name='planing',
            old_name='jour1',
            new_name='day1',
        ),
        migrations.RenameField(
            model_name='planing',
            old_name='jour2',
            new_name='day2',
        ),
        migrations.RenameField(
            model_name='planing',
            old_name='jour3',
            new_name='day3',
        ),
        migrations.RenameField(
            model_name='planing',
            old_name='jour4',
            new_name='day4',
        ),
        migrations.RenameField(
            model_name='planing',
            old_name='jour5',
            new_name='day5',
        ),
        migrations.RenameField(
            model_name='planing',
            old_name='jour6',
            new_name='day6',
        ),
        migrations.RenameField(
            model_name='planing',
            old_name='jour7',
            new_name='day7',
        ),
    ]
