# Generated by Django 3.0.3 on 2020-05-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0010_merge_20200526_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='phone',
        ),
        migrations.AddField(
            model_name='employe',
            name='phone1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='telephone 1'),
        ),
        migrations.AddField(
            model_name='employe',
            name='phone2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='telephone 2'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='finger_id',
            field=models.PositiveSmallIntegerField(blank=True, default='0231', unique=True),
            preserve_default=False,
        ),
    ]
