# Generated by Django 3.0.3 on 2020-06-01 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0011_auto_20200601_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planing',
            old_name='day1',
            new_name='diamanche',
        ),
        migrations.RenameField(
            model_name='planing',
            old_name='day2',
            new_name='jeudi',
        ),
        migrations.RenameField(
            model_name='planing',
            old_name='day4',
            new_name='lundi',
        ),
        migrations.RenameField(
            model_name='planing',
            old_name='day5',
            new_name='mardi',
        ),
        migrations.RenameField(
            model_name='planing',
            old_name='day3',
            new_name='mercredi',
        ),
        migrations.RenameField(
            model_name='planing',
            old_name='day6',
            new_name='samedi',
        ),
        migrations.RenameField(
            model_name='planing',
            old_name='day7',
            new_name='vendredi',
        ),
    ]
