# Generated by Django 3.0.3 on 2020-06-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0012_auto_20200601_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='jds',
            field=models.CharField(blank=True, choices=[(1, 'Samedi'), (2, 'Dimanche'), (3, 'Lundi'), (4, 'Mardi'), (5, 'Mercredi'), (6, 'Jeudi'), (7, 'Vendredi')], max_length=50, null=True),
        ),
    ]
