# Generated by Django 3.0.3 on 2020-06-02 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0014_auto_20200602_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planing',
            old_name='diamanche',
            new_name='day1',
        ),
        migrations.RenameField(
            model_name='planing',
            old_name='jeudi',
            new_name='day2',
        ),
        migrations.RenameField(
            model_name='planing',
            old_name='lundi',
            new_name='day3',
        ),
        migrations.RenameField(
            model_name='planing',
            old_name='mardi',
            new_name='day4',
        ),
        migrations.RenameField(
            model_name='planing',
            old_name='mercredi',
            new_name='day5',
        ),
        migrations.RenameField(
            model_name='planing',
            old_name='samedi',
            new_name='day6',
        ),
        migrations.RenameField(
            model_name='planing',
            old_name='vendredi',
            new_name='day7',
        ),
    ]
