# Generated by Django 3.0.3 on 2020-06-02 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0016_day_titre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='jds',
        ),
    ]
