# Generated by Django 3.0.3 on 2020-06-02 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0017_remove_day_jds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planing',
            name='day1',
        ),
        migrations.RemoveField(
            model_name='planing',
            name='day2',
        ),
        migrations.RemoveField(
            model_name='planing',
            name='day3',
        ),
        migrations.RemoveField(
            model_name='planing',
            name='day4',
        ),
        migrations.RemoveField(
            model_name='planing',
            name='day5',
        ),
        migrations.RemoveField(
            model_name='planing',
            name='day6',
        ),
        migrations.RemoveField(
            model_name='planing',
            name='day7',
        ),
        migrations.AddField(
            model_name='day',
            name='jds',
            field=models.CharField(blank=True, choices=[('SAMEDI', 'Samedi'), ('DIMANCHE', 'Dimanche'), ('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='planing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pointage.Day'),
        ),
    ]
