# Generated by Django 3.0.3 on 2020-06-02 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0018_auto_20200602_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='titre',
        ),
        migrations.AlterField(
            model_name='day',
            name='planing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pointage.Planing'),
        ),
    ]
